[package]
name = "rust-study"
version = "0.1.0"
authors = ["whr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tokio =  "0.2"
jsonpath_lib = "0.2.5"
serde_json = "1.0.57"
tokio = { version = "0.2", features = ["full"] }

