use std::collections::HashMap;

#[tokio::test]
async fn req_1() -> Result<(), Box<dyn std::error::Error>> {
    // let url = "http://www.zgei.com";
    // let resp = reqwest::Client::new()
    //     .post(url)
    //     .form(&[
    //         ("input", "在那遥远的地方"),
    //         ("filter", "name"),
    //         ("type", "netease"),
    //         ("page", "1"),
    //     ])
    //     .send()
    //     .await?;
    // // .json::<HashMap<String, String>>()
    // // .await?;
    // let text = resp.text().await?;
    // println!("{:#?}", text);
    Ok(())
}
